apiVersion: v1
kind: Pod
metadata:
  name: perf-locust-sde-benchmark
  namespace: sde-benchmark
  labels:
    app: locust-sde-benchmark
spec:
  containers:
  - name: locust
    image: perf-locust:latest
    imagePullPolicy: Never
    command: ["sleep"]
    args: ["infinity"]
    stdin: true
    tty: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
  restartPolicy: Always