apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/kafka
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/zookeeper